# Generated by Django 5.2.4 on 2025-07-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='power',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='statement',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
